/* AUTO-GENERATED by scripts/gen-i18n.mjs — do not edit by hand. */
import af from './af.json';
import ar from './ar.json';
import bg from './bg.json';
import bn from './bn.json';
import ca from './ca.json';
import cs from './cs.json';
import da from './da.json';
import de from './de.json';
import el from './el.json';
import es from './es.json';
import et from './et.json';
import fa from './fa.json';
import fi from './fi.json';
import fil from './fil.json';
import fr from './fr.json';
import he from './he.json';
import hi from './hi.json';
import hr from './hr.json';
import hu from './hu.json';
import id from './id.json';
import is from './is.json';
import it from './it.json';
import ja from './ja.json';
import ko from './ko.json';
import lt from './lt.json';
import lv from './lv.json';
import ms from './ms.json';
import nl from './nl.json';
import no from './no.json';
import pl from './pl.json';
import pt from './pt.json';
import ro from './ro.json';
import ru from './ru.json';
import sk from './sk.json';
import sr from './sr.json';
import sv from './sv.json';
import sw from './sw.json';
import th from './th.json';
import tr from './tr.json';
import uk from './uk.json';
import ur from './ur.json';
import vi from './vi.json';
import zh from './zh.json';

// Loosely typed on purpose: a translation may lag the English source by a few keys; i18n.ts
// deep-merges each over English, so any missing key falls back to English rather than erroring.
export const TRANSLATIONS: Record<string, unknown> = {
  'af': af,
  'ar': ar,
  'bg': bg,
  'bn': bn,
  'ca': ca,
  'cs': cs,
  'da': da,
  'de': de,
  'el': el,
  'es': es,
  'et': et,
  'fa': fa,
  'fi': fi,
  'fil': fil,
  'fr': fr,
  'he': he,
  'hi': hi,
  'hr': hr,
  'hu': hu,
  'id': id,
  'is': is,
  'it': it,
  'ja': ja,
  'ko': ko,
  'lt': lt,
  'lv': lv,
  'ms': ms,
  'nl': nl,
  'no': no,
  'pl': pl,
  'pt': pt,
  'ro': ro,
  'ru': ru,
  'sk': sk,
  'sr': sr,
  'sv': sv,
  'sw': sw,
  'th': th,
  'tr': tr,
  'uk': uk,
  'ur': ur,
  'vi': vi,
  'zh': zh,
};
